### ISSUE TITLE
jCal JSON format

### ISSUE THREAD

**Issue by carcohcal** [ical4j/ical4j-serializer#11]
Hi,

I'm trying to use the jCal JSON example but it isn't working:

```
Calendar calendar = ...;
SimpleModule module = new SimpleModule();
module.addSerializer(Calendar.class, new JCalSerializer());
ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(module);

String serialized = mapper.writeValueAsString(calendar);
```

The first issue I encounter is the need to set an entry parameter in the JCalSerializer.

![Jcal_error](https://user-images.githubusercontent.com/78375613/145726982-febee614-1f7a-4ea9-8eb5-f2d2e92509b4.png)

I added Calendar.class and compiles OK but while executing the following exception occurs in this line

` String serialized = mapper.writeValueAsString(calendar);`

```
java.lang.NoSuchMethodError: net.fortuna.ical4j.model.PropertyList.iterator()Ljava/util/Iterator;
	at org.mnode.ical4j.serializer.JCalSerializer.buildVCalendar(JCalSerializer.java:36) ~[ical4j-serializer-0.1.6.jar:na]
	at org.mnode.ical4j.serializer.JCalSerializer.serialize(JCalSerializer.java:26) ~[ical4j-serializer-0.1.6.jar:na]
	at org.mnode.ical4j.serializer.JCalSerializer.serialize(JCalSerializer.java:18) ~[ical4j-serializer-0.1.6.jar:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4569) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3822) ~[jackson-databind-2.13.0.jar:2.13.0]
```

I check the calendar and it has properties and components. 
I don't know if I'm doing something wrong or there is a bug. 

Thanks

**Comment by benfortuna** [comment]
Thanks for the early feedback. 

Can you confirm which version of ical4j you are using? The tests are currently run with ical4j v3.1.1.

**Comment by carcohcal** [comment]
> Thanks for the early feedback.
> 
> Can you confirm which version of ical4j you are using? The tests are currently run with ical4j v3.1.1.

Hi,

I'm using gradle with the following versions:

'org.mnode.ical4j:ical4j:4.0.0-alpha9'
'org.mnode.ical4j:ical4j-serializer:0.1.6'

**Comment by benfortuna** [comment]
Unfortunately ical4j v4 has a number of incompatible API changes that are not yet supported in ical4j-serializer. Once the final release of v4 is announced we will look to transition other libraries to the new API.

**Comment by carcohcal** [comment]
> Unfortunately ical4j v4 has a number of incompatible API changes that are not yet supported in ical4j-serializer. Once the final release of v4 is announced we will look to transition other libraries to the new API.

Thanks. Great API btw

**Comment by carcohcal** [comment]
I change ical API version ical -> json works find but now have an issue with the json -> ical conversion. 

I have the following function: 
```
private void JSONaIcal(String json) throws JsonMappingException, JsonProcessingException {
		
		ObjectMapper mapper = new ObjectMapper();

		SimpleModule module = new SimpleModule();
		module.addDeserializer(Calendar.class, new JCalMapper(Calendar.class));
		mapper.registerModule(module);

		Calendar calendar = mapper.readValue(json, Calendar.class);

	}
```


But the following error occurs:


```
Servlet.service() for servlet [dispatcherServlet] in context with path [/guardians/api] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Invalid input: null] with root cause

java.lang.IllegalArgumentException: Invalid input: null
	at org.mnode.ical4j.serializer.JsonMapper.assertTextValue(JsonMapper.java:36) ~[ical4j-serializer-0.1.6.jar:na]
	at org.mnode.ical4j.serializer.JCalMapper.deserialize(JCalMapper.java:40) ~[ical4j-serializer-0.1.6.jar:na]
	at org.mnode.ical4j.serializer.JCalMapper.deserialize(JCalMapper.java:19) ~[ical4j-serializer-0.1.6.jar:na]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3630) ~[jackson-databind-2.13.0.jar:2.13.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3598) ~[jackson-databind-2.13.0.jar:2.13.0]
```


I don't know if the JSON format but I just copy the one that the serializer generate

Thanks
